default_train:
    name: [Generic_kitti]
    path: [data/Generic_kitti]
    split: ['']
    context: [-1,1]
    cameras: [[0]]
    labels: []
    repeat: [1]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [192,640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 12
default_validation:
    name: [Generic_kitti]
    path: [data/Generic_kitti]
    split: ['']
    context: []
    cameras: [[0]]
    labels: []
    augmentation:
        resize: [192,640]
    dataloader:
        batch_size: 1
        pin_memory: True
        num_workers: 12
