wrapper:
    recipe: wrapper|default
arch:
    model:
        file: depth/SelfSupervisedModel
        use_gt_intrinsics: False
    networks:
        depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [0.1,100.0]
        pose:
            recipe: networks/pose_net|default
        intrinsics:
            file: intrinsics/IntrinsicsNet
            camera_model: 'UCM'
            shape: [ 192, 640 ]
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
optimizers:
    depth:
        recipe: optimizers|adam_20_05
        lr: 0.0002
    pose:
        recipe: optimizers|adam_20_05
        lr: 0.0002
    intrinsics:
        recipe: optimizers|adam_20_05
        lr: 0.001
datasets:
    train:
        recipe: datasets/generic_kitti|default_train
        dataloader:
            batch_size: 2
    validation:
        recipe: datasets/generic_kitti|default_validation
checkpoint:
    folder: /data/vidar/checkpoints        # Local folder to store checkpoints
    save_code: False                      # Save repository folder as well
    keep_top: 10                           # How many checkpoints should be stored