wrapper:
    recipe: wrapper|default
    max_epochs: 1
arch:
    model:
        file: depth/SelfSupervisedModel
    networks:
        depth:
            recipe: networks/mono_depth_res_net|default
            depth_range: [0.1,100.0]
        pose:
            recipe: networks/pose_net|default
    losses:
        reprojection:
            recipe: losses/reprojection|default
        smoothness:
            recipe: losses/smoothness|default
evaluation:
    depth:
        recipe: evaluation/depth|kitti_resize
optimizers:
    depth:
        recipe: optimizers|adam_20_05
    pose:
        recipe: optimizers|adam_20_05
datasets:
    train:
        recipe: datasets/kitti_tiny|train_selfsup_mr
    validation:
        recipe: datasets/kitti_tiny|validation_mr
checkpoint:
    folder: /data/vidar/checkpoints        # Local folder to store checkpoints
    save_code: False                      # Save repository folder as well
    keep_top: 10                           # How many checkpoints should be stored
